name: openTEPES-tutorial
channels:
          - defaults
dependencies:
          - python
          - altair
          - matplotlib
          - numpy
          - openTEPES
          - pandas
          - psutil
          - conda-forge::pyomo
          - rise
          - vega
          - vega_datasets
