name: openTEPES-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - glpk
  - coincbc
  - rise
  - numpy<2
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pip:
    - numpy<2
    - openTEPES
    - tsam
    - highspy
    - scikit-learn-extra
