name: openTEPES-tutorial
channel:
#  - defaults
#  - conda-forge
  - gurobi
dependencies:
          - python =3.8
          - altair
          - cartopy
          - coincbc
          - gurobi
          - matplotlib
          - numpy
          - pandas
          - pip
          - psutil
          - pyomo
          - pyscipopt
          - rise
          - vega
          - vega_datasets
          - pip:
              - openTEPES
              - scipy
