name: openTEPES-tutorial
dependencies:
          - python =3.8
          - altair
          - cartopy
          - coincbc
          - colour
          - matplotlib
          - numpy
          - pandas
          - pip
          - plotly
          - psutil
          - pyomo
          - pyscipopt
          - scikit-learn
          - scikit-learn-extra
          - rise
          - vega
          - vega_datasets
          - pip:
              - docker
              - openTEPES=4.3.2rc1
              - scipy
