name: openTEPES-tutorial
dependencies:
          - python =3.8
          - altair
          - cartopy
          - coincbc
          - matplotlib
          - numpy
          - pandas
          - pip
          - psutil
          - pyomo
          - pyscipopt
          - rise
          - vega
          - vega_datasets
          - pip:
              - openTEPES
              - scipy
