name: openTEPES-tutorial
dependencies:
          - python
          - altair
          - matplotlib
          - numpy
          - pandas
          - pip
          - psutil
          - pyomo
          - rise
          - vega
          - vega_datasets
