name: openTEPES-tutorial
dependencies:
          - python = 3.12.*
          - altair
          - cartopy
          - coincbc
          - colour
          - glpk
          - matplotlib
          - numpy
          - pandas
          - pip
          - plotly
          - psutil
          - pyomo
          - pyscipopt
          - scikit-learn
          - scikit-learn-extra
          - rise
          - vega
          - vega_datasets
          - pip:
              - docker
              - openTEPES
              - scipy
              - highspy
